// Import the shared makeRequest helper to keep HTTP calls consistent.
import { makeRequest } from "../client";
// Import centralized endpoint map to avoid scattering literal strings.
import { endpoints } from "../endpoints";

// Describe the backend response for status counts (live/upcoming/completed).
export type SuperAdminEventsStatusCounts = {
  // Total number of live events.
  live: number;
  // Total number of upcoming events.
  upcoming: number;
  // Total number of completed events.
  completed: number;
};

// Represent a single event row returned to the super admin.
export type SuperAdminEventListItem = {
  // Unique identifier generated by the backend.
  event_id: number;
  // Human readable title of the event.
  event_title: string;
  // HTML description string (render cautiously).
  description: string;
  // Current lifecycle status (live/upcoming/completed).
  status: string;
  // Event date already formatted as d-m-Y by backend.
  date: string;
  // Event time string (HH:mm).
  time: string;
  // Total attendee count the backend calculated.
  attendees: number;
  // Venue name tied to the event.
  venue_name: string;
  // Revenue amount aggregated for the event.
  revenue: number;
  // Relative thumbnail path to resolve via storage utils.
  thumbnail: string | null;
  // Flag indicating if event is hidden by admin.
  is_hidden_by_admin?: boolean;
  // Reason for hiding the event (only present if hidden).
  hidden_reason?: string | null;
  // Timestamp when event was hidden (formatted as d-m-Y H:i:s).
  hidden_at?: string | null;
};

// Shape of the pagination object included in the payload.
export type SuperAdminEventsPagination = {
  // Total number of records available server-side.
  total_records: number;
  // Currently active page index (1-based).
  current_page: number;
  // Total number of pages based on page size.
  total_pages: number;
  // Next page number when available, otherwise null.
  next_page: number | null;
  // Previous page number when available, otherwise null.
  prev_page: number | null;
};

// Aggregate response returned by /get_super_admin_events_list.
export type SuperAdminEventsResponse = {
  // Informational success message from backend.
  message: string;
  // Status counts object for summary widgets.
  status_counts: SuperAdminEventsStatusCounts;
  // Array of event rows for the current page.
  events: SuperAdminEventListItem[];
  // Pagination metadata to drive controls.
  pagination: SuperAdminEventsPagination;
};

// Parameters supported by getSuperAdminEventsList (sent in POST request body).
export type GetSuperAdminEventsParams = {
  // Page number requested (defaults to 1).
  page?: number;
  // Optional number of records per page.
  per_page?: number;
  // Filter by event status: "live" | "upcoming" | "completed".
  status?: "live" | "upcoming" | "completed";
  // Optional search term (event name, category, host, etc.).
  search?: string;
  // Optional filter for reported events only (true/false).
  reported_events?: boolean;
  // Optional filter by business intersection id (from get_business_intersections).
  business_intersection_id?: number;
  // Optional filter: events from this date (YYYY-MM-DD).
  date_from?: string;
  // Optional filter: events until this date (YYYY-MM-DD).
  date_to?: string;
  // Optional filter by event category id (from get_event_categories).
  event_category_id?: number;
  // Optional filter by venue city name.
  city?: string;
  // Optional filter by venue state name.
  state?: string;
  // Optional filter by venue postal code.
  postal_code?: string;
};

/**
 * Fetch paginated events for the super admin view.
 * Sends all parameters in POST body (page, per_page, status, optional filters).
 * @param params - Optional pagination and filter params.
 * @returns Promise resolving to the events payload.
 */
export const getSuperAdminEventsList = async (
  params?: GetSuperAdminEventsParams
): Promise<SuperAdminEventsResponse> => {
  // Normalize the requested page with a default of 1.
  const page = params?.page ?? 1;
  // Build request body with required and optional fields; backend expects body.
  const body: Record<string, number | boolean | string> = { page };
  // Append per_page when provided by the caller.
  if (params?.per_page != null) {
    body.per_page = params.per_page;
  }
  // Append status when provided (drives live/upcoming/completed tab).
  if (params?.status) {
    body.status = params.status;
  }
  // Append search only when non-empty string.
  if (params?.search != null && params.search.trim() !== "") {
    body.search = params.search.trim();
  }
  // Append reported_events only when filter is explicitly true or false.
  if (params?.reported_events !== undefined) {
    body.reported_events = params.reported_events;
  }
  // Append business_intersection_id only when a numeric filter is selected.
  if (params?.business_intersection_id != null) {
    body.business_intersection_id = params.business_intersection_id;
  }
  // Append date_from only when provided.
  if (params?.date_from) {
    body.date_from = params.date_from;
  }
  // Append date_to only when provided.
  if (params?.date_to) {
    body.date_to = params.date_to;
  }
  // Append category_id only when a category filter is selected.
  if (params?.event_category_id != null) {
    body.category_id = params.event_category_id;
  }
  // Append city only when a non-empty value is provided.
  if (params?.city && params.city.trim() !== "") {
    body.city = params.city.trim();
  }
  // Append state only when a non-empty value is provided.
  if (params?.state && params.state.trim() !== "") {
    body.state = params.state.trim();
  }
  // Append postal_code only when a non-empty value is provided.
  if (params?.postal_code && params.postal_code.trim() !== "") {
    body.postal_code = params.postal_code.trim();
  }
  // Execute POST request with body through makeRequest helper.
  return makeRequest<SuperAdminEventsResponse>(
    endpoints.superAdminEvents,
    "POST",
    body
  );
};

// Describe a single media record returned in the event details payload.
export type SuperAdminEventMediaItem = {
  // Unique media identifier for reference.
  event_media_id: number;
  // Media type string (thumbnail/banner/flyer/video).
  media_type: string;
  // Relative storage path to resolve via file utils.
  file_path: string;
  // Original file name stored for info tooltips.
  file_name: string;
  // File size in bytes useful for download info.
  file_size: number;
};

// Group the media arrays keyed by media type.
export type SuperAdminEventMedia = {
  // Thumbnail asset array (usually single entry).
  thumbnail: SuperAdminEventMediaItem[];
  // Banner asset array.
  banner: SuperAdminEventMediaItem[];
  // Flyer asset array.
  flyer: SuperAdminEventMediaItem[];
  // Video asset array.
  video: SuperAdminEventMediaItem[];
};

// Represent a social media link row for the event.
export type SuperAdminEventSocialLink = {
  // Unique identifier for the social link.
  event_social_media_id: number;
  // Platform identifier string (facebook/instagram/etc.).
  platform: string;
  // Public URL for the platform profile/post.
  url: string;
};

// Describe a single ticket row returned by the API.
export type SuperAdminEventTicket = {
  // Ticket identifier (matches backend ticket table).
  ticket_id: number;
  // Ticket category identifier.
  ticket_category_id: number;
  // Human readable category name.
  category_name: string;
  // Ticket type string (single_entry, etc).
  ticket_type: string;
  // Rich description string or null when absent.
  description: string | null;
  // Price string formatted by backend.
  price: string;
  // Total quantity available for sale.
  total_available: number;
  // Sold quantity reported by backend.
  sold_quantity: number;
  // Ticket info helper text.
  ticket_info: string | null;
  // Maximum quantity allowed per user.
  max_per_user: number;
};

// Describe the venue block returned by the endpoint.
export type SuperAdminEventVenue = {
  // Venue identifier.
  venue_id: number;
  // Venue name string.
  venue_name: string;
  // Full address line.
  venue_address: string;
  // City value.
  city: string;
  // State or province string.
  state_province: string;
  // Postal code string.
  postal_code: string;
  // Country string.
  country: string;
  // Latitude string value for mapping.
  latitude: string | null;
  // Longitude string value for mapping.
  longitude: string | null;
  // Maximum attendees allowed.
  maximum_attendees: number;
  // Additional venue details.
  additional_details: string | null;
  // Optional venue image path.
  venue_image: string | null;
};

// Represent a single artist entry.
export type SuperAdminEventArtist = {
  // Unique artist identifier.
  event_artist_id: number;
  // Display name for the artist.
  artist_name: string;
  // Relative image path or null.
  artist_image: string | null;
  // Optional social links array (structure unknown so fallback to Record).
  social_media: Array<Record<string, unknown>>;
};

// Represent the terms block for the event.
export type SuperAdminEventTerms = {
  // Terms identifier.
  event_terms_id: number;
  // Rich text terms content string.
  terms_content: string;
};

// Represent a coupon row tied to the event.
export type SuperAdminEventCoupon = {
  // Coupon identifier.
  coupon_id: number;
  // Coupon code string.
  coupon_code: string;
  // Discount type string (percentage/flat).
  discount_type: string;
  // Percentage discount as string.
  discount_percent: string | null;
  // Max cap discount string.
  max_cap_discount: string | null;
  // Flat discount amount string.
  flat_discount_amount: string | null;
  // Max times the coupon can be used.
  max_times_applicable: number;
  // Coupon validity start date in d-m-Y format.
  start_date: string;
  // Coupon validity end date in d-m-Y format.
  end_date: string;
  // Total times the coupon has been used.
  times_used: number;
};

// Describe the host information block in event details (minimal shape).
export type SuperAdminEventDetailsHost = {
  // Host identifier.
  host_user_id: number;
  // Host first name.
  first_name: string;
  // Host last name.
  last_name: string;
  // Host email address.
  email: string;
  // Optional business object.
  business?: {
    // Business name string.
    business_name: string;
    // Account type string.
    account_type: string;
    // Optional industry string.
    industry: string | null;
    // Optional company size string.
    company_size: string | null;
  } | null;
};

// Represent the primary event info block.
export type SuperAdminEventCore = {
  // Event identifier.
  event_id: number;
  // Event title string.
  event_title: string;
  // Rich description string.
  description: string;
  // Related category identifier.
  event_category_id: number;
  // Start date string formatted as d-m-Y.
  start_date: string;
  // End date string formatted as d-m-Y.
  end_date: string;
  // Start time string (HH:mm).
  start_time: string;
  // End time string (HH:mm).
  end_time: string;
  // Key highlights HTML string.
  key_highlights: string | null;
};

// Overall payload returned by get_super_admin_event_details.
export type SuperAdminEventDetailsResponse = {
  // Descriptive message from backend.
  message: string;
  // Event core data block.
  event: SuperAdminEventCore;
  // Media grouped by type.
  media: SuperAdminEventMedia;
  // Social media links array.
  social_media: SuperAdminEventSocialLink[];
  // Tickets array.
  tickets: SuperAdminEventTicket[];
  // Venue information (can be null).
  venue: SuperAdminEventVenue | null;
  // Artists array (may be empty).
  artists: SuperAdminEventArtist[];
  // Terms block (can be null).
  terms: SuperAdminEventTerms | null;
  // Coupons array.
  coupons: SuperAdminEventCoupon[];
  // Host info block (minimal shape for event details).
  host: SuperAdminEventDetailsHost;
};

/**
 * Fetch a detailed event record for the provided identifier.
 * @param eventId - Unique identifier of the event to retrieve.
 */
export const getSuperAdminEventDetails = async (
  eventId: number
): Promise<SuperAdminEventDetailsResponse> => {
  // Execute a GET request including event_id as query parameter.
  return makeRequest<SuperAdminEventDetailsResponse>(
    endpoints.superAdminEventDetails,
    "GET",
    undefined,
    { params: { event_id: eventId } }
  );
};

// Define the business profile block returned for each host.
export type SuperAdminEventHostBusiness = {
  // Business name string or null when host is personal.
  business_name: string | null;
  // Industry label or null.
  industry: string | null;
  // Country name string or null.
  country_name: string | null;
};

// Define the metrics block summarizing host performance.
export type SuperAdminEventHostMetrics = {
  // Total events created by the host.
  events_created: number;
  // Total live events currently on platform.
  events_live: number;
  // Total completed events.
  events_completed: number;
  // Total revenue generated by host events.
  total_revenue_generated: number;
  // Total tickets sold across events.
  total_tickets_sold: number;
  // Number of reports submitted against this host.
  reports_count: number;
};

// Define the core host record returned by the API.
export type SuperAdminEventHost = {
  // Unique host identifier.
  host_user_id: number;
  // Host first name string.
  first_name: string;
  // Host last name string.
  last_name: string;
  // Primary email address.
  email: string;
  // Optional phone number string.
  phone_number: string | null;
  // Account type string (business/personal) or null.
  account_type: string | null;
  // Flag indicating if host completed business profile.
  has_business_profile: boolean;
  // Embedded business profile block.
  business: SuperAdminEventHostBusiness;
  // Embedded metrics block.
  metrics: SuperAdminEventHostMetrics;
  // Last login timestamp string or null.
  last_login: string | null;
  // Flag indicating if host is blocked by admin.
  is_blocked?: boolean;
  // Reason for blocking the host (only present if blocked).
  blocked_reason?: string | null;
  // Timestamp when host was blocked (formatted as d-m-Y H:i:s).
  blocked_at?: string | null;
  // Super admin user id who blocked the host (when blocked).
  blocked_by_super_admin_id?: number | null;
  // Business intersection id (from get_business_intersections).
  business_intersection_id?: number | null;
  // Business intersection display name (e.g. "Woman-owned").
  business_intersection?: string | null;
};

// Pagination metadata for hosts list.
export type SuperAdminEventHostsPagination = {
  // Total number of host records available.
  total_records: number;
  // Current page number (1-indexed).
  current_page: number;
  // Total pages count.
  total_pages: number;
  // Next page number when available.
  next_page: number | null;
  // Previous page number when available.
  prev_page: number | null;
};

// Response payload returned by get_super_admin_event_hosts_list.
export type SuperAdminEventHostsResponse = {
  // Informational success message.
  message: string;
  // Array of host records.
  hosts: SuperAdminEventHost[];
  // Pagination metadata.
  pagination: SuperAdminEventHostsPagination;
};

// Parameters supported by getSuperAdminEventHostsList (sent in request body).
export type GetSuperAdminEventHostsParams = {
  // Page number requested.
  page?: number;
  // Optional number of records per page (defaults to backend default, typically 30).
  per_page?: number;
  // Optional filter by business intersection id (from get_business_intersections).
  business_intersection_id?: number;
  // Optional filter by whether host has reports (true/false).
  has_reports?: boolean;
  // Optional filter by account type: "business" or "personal".
  account_type?: string;
  // Optional filter by state id (from get_state list).
  state_id?: number;
  // Optional filter by host zipcode.
  zipcode?: string;
};

/**
 * Fetch paginated event hosts list for the super admin panel.
 * Sends all parameters in POST body (page, per_page, optional filters).
 * @param params - Optional pagination and filter params.
 */
export const getSuperAdminEventHostsList = async (
  params?: GetSuperAdminEventHostsParams
): Promise<SuperAdminEventHostsResponse> => {
  // Normalize the requested page with a default of 1.
  const page = params?.page ?? 1;
  // Build request body with page and optional fields; backend expects body.
  const body: Record<string, number | boolean | string> = { page };
  // Append per_page when provided by the caller.
  if (params?.per_page != null) {
    body.per_page = params.per_page;
  }
  // Append business_intersection_id only when a numeric filter is selected.
  if (params?.business_intersection_id != null) {
    body.business_intersection_id = params.business_intersection_id;
  }
  // Append has_reports only when filter is explicitly true or false.
  if (params?.has_reports !== undefined) {
    body.has_reports = params.has_reports;
  }
  // Append account_type only when filter is business or personal.
  if (params?.account_type === "business" || params?.account_type === "personal") {
    body.account_type = params.account_type;
  }
  // Append state_id only when a numeric filter is selected.
  if (params?.state_id != null) {
    body.state_id = params.state_id;
  }
  // Append zipcode only when a non-empty value is provided.
  if (params?.zipcode && params.zipcode.trim() !== "") {
    body.zipcode = params.zipcode.trim();
  }
  // Execute POST request with body through makeRequest helper.
  return makeRequest<SuperAdminEventHostsResponse>(
    endpoints.superAdminEventHosts,
    "POST",
    body
  );
};

// Request payload for toggling event host block status.
export type ToggleEventHostBlockStatusRequest = {
  // Unique identifier of the event host to block/unblock.
  host_user_id: number;
  // Action to perform: "block" or "unblock".
  action: "block" | "unblock";
  // Optional reason for blocking (max 500 characters). Not required for unblock.
  reason?: string | null;
};

// Response payload for toggling event host block status.
export type ToggleEventHostBlockStatusResponse = {
  // Success message from backend.
  message: string;
};

/**
 * Toggle event host block/unblock status.
 * Blocks or unblocks an event host with optional reason.
 * @param payload - Request payload containing host_user_id, action, and optional reason.
 * @returns Promise resolving to the response with success message.
 */
export const toggleEventHostBlockStatus = async (
  payload: ToggleEventHostBlockStatusRequest
): Promise<ToggleEventHostBlockStatusResponse> => {
  // Execute POST request through makeRequest helper.
  return makeRequest<ToggleEventHostBlockStatusResponse>(
    endpoints.toggleEventHostBlockStatus,
    "POST",
    payload
  );
};

// Request payload for toggling event hide status.
export type ToggleEventHideStatusRequest = {
  // Unique identifier of the event to hide/unhide.
  event_id: number;
  // Action to perform: "hide" or "unhide".
  action: "hide" | "unhide";
  // Optional reason for hiding (max 500 characters). Not required for unhide.
  reason?: string | null;
};

// Response payload for toggling event hide status.
export type ToggleEventHideStatusResponse = {
  // Success message from backend.
  message: string;
};

/**
 * Toggle event hide/unhide status.
 * Hides or unhides a published event with optional reason.
 * Only published events can be hidden.
 * @param payload - Request payload containing event_id, action, and optional reason.
 * @returns Promise resolving to the response with success message.
 */
export const toggleEventHideStatus = async (
  payload: ToggleEventHideStatusRequest
): Promise<ToggleEventHideStatusResponse> => {
  // Execute POST request through makeRequest helper.
  return makeRequest<ToggleEventHideStatusResponse>(
    endpoints.toggleEventHideStatus,
    "POST",
    payload
  );
};


