<?php

namespace App\Documentation\Swagger\SuperAdmin;

/**
 * @OA\Post(
 *     path="/v1/create_cms_page",
 *     summary="Create New CMS Page",
 *     description="Allows an authenticated Super Admin to create a new CMS page with title, rich text content, and optional active status. The slug is automatically generated from the title to ensure URL-friendly format. If a slug conflict occurs, a unique slug is generated by appending a number. The content is stored as HTML from the WYSIWYG editor, preserving all formatting.",
 *     tags={"Super Admin API"},
 *     security={{"sanctum": {}}},
 *     @OA\RequestBody(
 *         required=true,
 *         @OA\MediaType(
 *             mediaType="application/json",
 *             @OA\Schema(
 *                 type="object",
 *                 required={"title", "content"},
 *                 @OA\Property(
 *                     property="title",
 *                     type="string",
 *                     maxLength=255,
 *                     example="Terms & Conditions",
 *                     description="CMS page title (e.g., 'Terms & Conditions', 'Privacy Policy', 'Legal Terms'). Must be unique. Validation rule: 'required|string|max:255|unique:cms_pages,title'."
 *                 ),
 *                 @OA\Property(
 *                     property="content",
 *                     type="string",
 *                     example="<p>This is the content of the Terms & Conditions page. It supports <strong>bold</strong>, <em>italic</em>, and other HTML formatting.</p>",
 *                     description="Rich text content from WYSIWYG editor. Stored as HTML format to preserve formatting (bold, italic, lists, links, etc.). Validation rule: 'required|string'."
 *                 ),
 *                 @OA\Property(
 *                     property="is_active",
 *                     type="boolean",
 *                     example=true,
 *                     description="Status flag to enable/disable page visibility. Default is true (active). If false, page will not appear in footer links. Validation rule: 'nullable|boolean'."
 *                 )
 *             ),
 *             @OA\Examples(
 *                 example="CreateTermsPage",
 *                 summary="Create Terms & Conditions Page",
 *                 value={
 *                     "title": "Terms & Conditions",
 *                     "content": "<h1>Terms & Conditions</h1><p>By using our platform, you agree to the following terms...</p>",
 *                     "is_active": true
 *                 }
 *             ),
 *             @OA\Examples(
 *                 example="CreatePrivacyPage",
 *                 summary="Create Privacy Policy Page",
 *                 value={
 *                     "title": "Privacy Policy",
 *                     "content": "<h1>Privacy Policy</h1><p>We respect your privacy and are committed to protecting your personal data...</p>",
 *                     "is_active": true
 *                 }
 *             )
 *         )
 *     ),
 *     @OA\Response(
 *         response=200,
 *         description="CMS page created successfully",
 *         @OA\JsonContent(
 *             type="object",
 *             @OA\Property(property="success", type="boolean", example=true),
 *             @OA\Property(
 *                 property="data",
 *                 type="object",
 *                 @OA\Property(property="message", type="string", example="CMS page created successfully"),
 *                 @OA\Property(
 *                     property="cms_page",
 *                     type="object",
 *                     @OA\Property(property="cms_page_id", type="integer", example=1),
 *                     @OA\Property(property="title", type="string", example="Terms & Conditions"),
 *                     @OA\Property(property="slug", type="string", example="terms-and-conditions"),
 *                     @OA\Property(property="content", type="string", example="<p>Rich text HTML content...</p>"),
 *                     @OA\Property(property="is_active", type="boolean", example=true),
 *                     @OA\Property(property="created_at", type="string", example="28-11-2025 12:00:00"),
 *                     @OA\Property(property="updated_at", type="string", example="28-11-2025 12:00:00")
 *                 )
 *             )
 *         )
 *     ),
 *     @OA\Response(
 *         response=400,
 *         description="Validation error (E001)",
 *         @OA\JsonContent(
 *             type="object",
 *             @OA\Property(property="success", type="boolean", example=false),
 *             @OA\Property(
 *                 property="error",
 *                 type="object",
 *                 @OA\Property(property="error_code", type="string", example="E001"),
 *                 @OA\Property(property="error_message", type="object", example={"title": {"The title field is required."}, "content": {"The content field is required."}})
 *             )
 *         )
 *     ),
 *     @OA\Response(
 *         response=401,
 *         description="Authentication error (E003)",
 *         @OA\JsonContent(
 *             type="object",
 *             @OA\Property(property="success", type="boolean", example=false),
 *             @OA\Property(
 *                 property="error",
 *                 type="object",
 *                 @OA\Property(property="error_code", type="string", example="E003"),
 *                 @OA\Property(property="error_message", type="string", example="Authentication required")
 *             )
 *         )
 *     ),
 *     @OA\Response(
 *         response=500,
 *         description="Server error (E002)",
 *         @OA\JsonContent(
 *             type="object",
 *             @OA\Property(property="success", type="boolean", example=false),
 *             @OA\Property(
 *                 property="error",
 *                 type="object",
 *                 @OA\Property(property="error_code", type="string", example="E002"),
 *                 @OA\Property(property="error_message", type="string", example="An error occurred while creating CMS page")
 *             )
 *         )
 *     )
 * )
 */
class CreateCmsPage
{
    // Empty class for Swagger annotations
}

